FROM golang:1.19

WORKDIR /app

COPY ./discordgo /usr/local/go/src/discordgo
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
COPY ./credentials/peeonabot.token ./credentials/discord.token
RUN go build -v -o /usr/local/bin/peeonabot ./*.go

CMD ["peeonabot"]
