FROM golang:1.19

WORKDIR /app

COPY go.mod go.sum ./
COPY ./discordgo /usr/local/go/src/discordgo
RUN go mod download && go mod verify

COPY . .
COPY ./credentials/peeonabot-test.token ./credentials/discord.token
RUN go build -v -o /usr/local/bin/peeonabot ./main.go ./movies.go

CMD ["peeonabot"]
